### ISSUE TITLE
Exported SVG Needs Cropping

### ISSUE THREAD

**Issue by thomasnield** [naveen521kk/manim-mobject-svg#7]
When I use this library, and I convert a MObject to SVG, the SVG is not cropped to its size and seems to render a whole scene. Is there an easy solution to this? Sorry I'm not familiar with Cairo otherwise I'd try to fix myself.

**Comment by naveen521kk** [comment]
Sorry for the late reply, missed this notification. I think adding a parameter called `crop` should do, which I think should be set to `True` by default. That parameter should crop the SVG based on the `height` and `width` of the mobject. I'll have a look into implementing it.

**Comment by thomasnield** [comment]
Thanks! That'd be lovely and thanks for developing this small but very useful utility.
