### ISSUE TITLE
Not compatible with Python 3.11

### ISSUE THREAD

**Issue by spectria-limina** [naveen521kk/manim-mobject-svg#8]
This module is not compatible with Python 3.11 so trying to install it is causing me an error.

**Comment by naveen521kk** [comment]
Can you tell what's the error when trying to use this with Python 3.11. I remember testing this out there.

**Comment by spectria-limina** [comment]
```$ pip3 install manim-mobject-svg
ERROR: Ignored the following versions that require a different python version: 0.1.0 Requires-Python >=3.8,<=3.11; 0.2.0 Requires-Python >=3.8,<=3.11
ERROR: Could not find a version that satisfies the requirement manim-mobject-svg (from versions: none)
ERROR: No matching distribution found for manim-mobject-svg
```

**Comment by naveen521kk** [comment]
I tried testing it locally and it seems to install just fine. Using some Google foo, I found a similar StackOverflow question https://stackoverflow.com/a/70347034/12858827, probably try updating pip, HTH.

**Comment by spectria-limina** [comment]
According to [this PEP](https://peps.python.org/pep-0440/#inclusive-ordered-comparison) the version should be extended with a zero, so I think `<= 3.11` is interpreted as `<= 3.11.0`.
